name: Push to ECR
description: Push to ECR with digest tag
inputs:
  aws-assume-role-arn:
    description: Assume Role ARN
    required: true
  aws-region:
    description: AWS Region
    required: true
  image:
    description: Image name
    required: true
  src-tag:
    description: Source image tag
    required: true
    default: latest
  dest-tag:
    description: Destination image tag
    required: true
  push-digest-tag:
    description: Push also digest tag (default: true)
    required: true
    default: true
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-assume-role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Push
      shell: bash
      run: |
        digest=${GITHUB_SHA::8}

        if [ "${{ inputs.push-digest-tag }}" = "true" ]; then
          docker tag \
            ${{ inputs.image }}:${{ inputs.src-tag }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image }}:${digest}
        fi

        docker tag \
          ${{ inputs.image }}:${{ inputs.src-tag }} \
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image }}:${{ inputs.dest-tag }}

        if [ "${{ inputs.push-digest-tag }}" = "true" ]; then
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image }}:${digest}
        fi

        docker push \
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image }}:${{ inputs.dest-tag }}
